#ifndef RESPONSE_HANDLER_RESPONSE_HANDLER_THREAD_PUBLIC_H
#define RESPONSE_HANDLER_RESPONSE_HANDLER_THREAD_PUBLIC_H

#include "../01-interface/01-IHttpRequestHandler.h"

#endif // RESPONSE_HANDLER_RESPONSE_HANDLER_THREAD_PUBLIC_H